# Generated by Django 3.1.7 on 2021-04-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20210404_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='element_type_icons', verbose_name='Иконка стихии'),
        ),
    ]
